language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install: python setup.py develop
script: nosetests
deploy:
  provider: pypi
  user: vanyasem
  password:
    secure: CB3yvV+eW+gFo+xFkVgwHDIU2n40GFD1w7aMRtKVuXhYe4kbR9gLB0D7O4kRawXqpe45t+4ZJMSoqiBfQVCDyRyLLIhGkvYKoN3Ap7B4udP43Qu2UO9W9Gnn+ZSUSC4CsZebybg1e8z5LYBu4M6mzqf+OTJFdFHSsuPMOxQZbbeWz9MA0HlFbSg0WWOUFK+26KdwDFD1mHXYvlyHXAG4pP6Zj1IgiQKCSy7gC4HOWUfo/4f9IZPglA+6wWENxQY1BEDxL8SwjJ42T6Ghuyy1mL2nVqN1BGcpkQbf5oXiNu5wfax0LnFE5G/XhV/ydfvNB56BXvcqwvP4YMe7V0F6fK/zE0Eb1RPqLPpKdWm9h4M/E3tah+6yCfFpwL98/BuqosQSstFCsyTZR1oVe+uwyeAKrcQF80q11WwOvYi8yMW9k0i6ABRHD3kDiO1gjtyBVcELhFjxoWmdbS9GkxMKWIUw/EiI/8NkYqWAbRkoG/vRAGCxGxZnMinpERcxCZ4Z21cTiVaERNDRxHZVG0QQziYqgZcZ1Cx+PcMSGlenzyQBWDGDR+JKrewoTR9SCscciUVVhPSE/GrcvSLbvUCXIWutJH+q/2rBb5q4s+7yzixQHpZ7tpi/elbi/SwW7g2RTsdA/WP3XJkaVgplGovv9mZfdIRQo/ojB5Yj2o0H2EM=
  on:
    tags: true
    branch: master